### ISSUE TITLE
Options and optimizations 

### ISSUE THREAD

**Issue by stevenhauser** [timkendrick/memoize-weak#1] opened 2016-12-05 22:06 UTC
Hey, this is a great project! I just wrote almost exactly the same code a couple weeks ago and only found your project today when I was going to open-source mine.

I'm wondering if you'd accept a PR for some additional functionality? There are a couple things that I think would be great to add:

1. A way to garbage collect primitives. This is something I ran up against, too. Currently if a `MapTree` has primitives in a branch there's no way for those primitives to be GC'd unless an "earlier" part in the branch is an object.
1. A way to GC the entire tree. The thinking behind this is you might have a bunch of objects still in memory that you no longer care about retaining their memoized value, but since the objects are still in memory their memoized values also stick around in memory, even if you no longer need them.
1. Perhaps a way to minimize the number of wrappers around arguments. Right now each argument generates a `MapTree`, a `Map`, and a `WeakMap`, some of which may not be used. I think at scale this may become a problem to generate unused objects, and to generate a `MapTree` for each argument, too. Maybe it makes sense to wait until this is a problem though.

The way I was going to address these problems in my implementation was to write some sort of `createMemoizer` function that might look like this:

```js
const createMemoizer = (opts = {}) => {
  const memoize = () => {
    const memoized = (...args) => {
      // Existing memoization code
      // Way to manage primitives, provided by `opts.managePrimitives`
      // or something, which could default to a noop.
    };
    // Clears out all primitives in `Map`s
    memoized.clearPrimitivesCache = () => {};
    // Clears out the entire cache by recreating the top-level tree.
    memoized.clearCache = () => {};
    return memoized;
  };
  return memoize;
};
```

One of the tricky things with `managePrimitives` and `clearPrimitivesCache` is that they are currently stored in a nested `MapTree` structure, so there's no easy way to clear those out. In my implementation the `Map` object is flat and might have multiple branches. For instance `'a'` could have branches of `'b'`, `'c'`, and `{}` in it, and then `map.clear()` could be called to trash all of those, thereby trashing them in any `WeakMaps`, too. Perhaps there's a downside to that approach I'm not seeing?

[Here's my implemention](https://gist.github.com/stevenhauser/aaabac27c4a6af0240e210a50f52d3af) if you're curious. I needed to fix a bug for when the return value is falsy and needed to add that clearing functionality, but you can see that `enforceSize` is the default (and arbitrary) implementation I had in mind for `managePrimitives`.

Anyway if you're open to collaboration I'd love to submit a PR to add some of this functionality. Let me know!

**Comment by timkendrick** [comment] 2017-04-17 15:37
Hi there @stevenhauser! Thanks for the great feedback. Really sorry for the ridiculously late reply – somehow I must have missed this issue when you filed it. Good to see somebody else has been grappling with the same problems. I imagine you've moved on with your life in the last few months but I thought I should probably respond to your comments (inspired by your suggestions, I've also hopefully [addressed these issues](https://github.com/timkendrick/memoize-weak/commit/4ca8508ab37ff10a912ca876e4bf5e54385153a5) in the most recent version).

Based on your points I've given some more thought to the issue of primitive arguments never being cleared. When developing this module I'd been working under the (false) assumption that primitive arguments were always going to be insignificant size-wise compared to object arguments, and therefore not worth cluttering the implementation for the sake of relatively minor gains. I hadn't considered that there are situations when the primitive arguments themselves might be pretty hefty (e.g. webpack transform functions that operate on a massive string of source-code) or where they're enormously high-volume (e.g. pre-computing normal values in a 3D engine) – in these situations you'd definitely want some way of clearing the cache of primitive arguments once they cease to be useful.

I couldn't come up with a silver-bullet solution to clearing the primitive cache automatically: I considered going down an LRU-style approach similar to your implementation, but having to pick an arbitrary cache size makes me a bit uneasy, seeing as it can lead to unpredictable behavior (e.g. the 1001st primitive key argument causing a totally-unrelated memoized result to be removed from the cache and re-computed next time it is needed). In the tradeoff between a primitive cache that grows over time if left unchecked vs the possibility of memoized functions being re-called unexpectedly, I reckon it's more important to prioritize the core behavior of never re-calling the underlying function when a memoized function is called with the same arguments, even if it means that primitive arguments can accumulate in the cache if they're not preceded by object arguments at the call site.

Having said this, you're totally right that there still needs to be some way of dealing with the edge cases, so I've added a `.clear()` method on the memoized function. When called with no arguments, it will clear the whole cache (both arguments and values). When called with multiple arguments (e.g. `.clear('foo')`, `.clear(foo, bar)` etc) it will clear everything at the specified path and below.

This means that if you just want to GC the entire tree (your second scenario) you can do that by calling the `.clear()` method with no arguments, while if you have particular garbage collection logic that you want to apply for specific primitive values (your first scenario if I understand correctly?), you come up with a more specific implementation that calls `.clear(...)` with the relevant primitives (e.g. after a file is deleted, or when discarding a 3D model, etc). I've left this as an undocumented feature for now, seeing as it complicates the simplicity of the API, but it's an important feature so it's not going anywhere.

I haven't addressed your third point, about minimizing the number of objects that are created: I agree that this could become a problem at scale (e.g. memoizing a `get3dLineLength(x1, y1, z1, x2, y2, z2)` function sounds like it'd be super-wasteful with the current implementation), but I decided it's more important to keep the implementation straightforward rather than rework it substantially to minimize object allocation (which comes with its own issues, e.g. how it affects the newly-implemented branch-level cache clearing). This package was intended as a dirt-simple general-purpose memoizer that you can just import for some quick performance wins and forget about, whereas if you're working at the scale where object allocations become a concern, then there are probably others that would be more suited for those use cases (as indeed would your implementation).

I hope that answers your comments – and thanks again for the thought you put into the feedback. I'll close this but feel free to re-open if needed.

Thanks!

**Closed as completed by timkendrick** 2017-04-17 15:37 UTC

**Comment by stevenhauser** [comment] 2017-04-17 21:08
Hey @timkendrick, thanks for the response! All of your points make sense to me—it's a tricky bit of code to deal with and I get how you want to keep it simple while still providing _some_ "power options" like `clear`. Thanks for adding that functionality, I'm sure it'll come in handy!
